version: '3.7'

services:

    puppeteer:
      build: ./backend/worker
      container_name: puppeteer
      env_file: 
        - ./backend/worker/.env
    

    postgres:
        build: ./backend/src/db
        container_name: postgres
        ports:
            - 5050:5432   
        volumes: 
            - volume-db:/var/lib/postgresql/data

    backend:
        build: ./backend
        depends_on: 
            - postgres
        container_name: backend
        env_file: 
        - ./backend/worker/.env
        depends_on: 
            - postgres
        ports:
            - 9090:8080

    frontend:
        container_name: frontend
        build: ./frontend
        container_name: frontend
        env_file: 
            - ./frontend/.env
        ports:
            - 1337:80

volumes:
    volume-db: